import { Horse } from "./horse.model";

export const MOCKHORSES: any[] = [
    {   "id": 1,
        "name": "Thunder",
        "height": "14.5 hands",
        "age": 5,
        "weight": 900,
        "breed": "Arabian",
        "color": "Chestnut",
        "gender": "Mare",
        "imageUrl": "../../assets/images/owned/chestnutArabian.webp"
    },
    {   "id": 2,
        "name": "Hollywood Spirit",
        "height": "15.2 hands",
        "age": 8,
        "weight": 1250,
        "breed": "Quarter Horse",
        "color": "Bay",
        "gender": "Stallion",
        "imageUrl": "../../assets/images/owned/bayQuarterHorse.webp"
    },
    {   "id": 3,
        "name": "Midnight",
        "height": "17 hands",
        "age": 6,
        "weight": 1300,
        "breed": "Friesian",
        "color": "Black",
        "gender": "Mare",
        "imageUrl": "../../assets/images/owned/fressian-mare.webp"
    },
    {   "id": 4,
        "name": "Grace",
        "height": "17 hands",
        "age": 4,
        "weight": 1200,
        "breed": "Thoroughbred",
        "color": "Gray",
        "gender": "Mare",
        "imageUrl": "../../assets/images/owned/thoroughbred-mare.webp"
    },
    {   "id": 5,
        "name": "Duke",
        "height": "16 hands",
        "age": 10,
        "weight": 1150,
        "breed": "Andalusian",
        "color": "Gray",
        "gender": "Stallion",
        "imageUrl": "../../assets/images/owned/andalusian-stallion.webp"
    },
    {   "id": 6,
        "name": "Bella",
        "height": "15.3 hands",
        "age": 3,
        "weight": 1850,
        "breed": "Suffolk Punch",
        "color": "Chestnut",
        "gender": "Mare",
        "imageUrl": "../../assets/images/owned/suffolk-punch-mare.webp"
    },
    {   "id": 7,
        "name": "Max",
        "height": "18 hands",
        "age": 7,
        "weight": 2100,
        "breed": "Shire",
        "color": "Black",
        "gender": "Gelding",
        "imageUrl": "../../assets/images/owned/shire-male.webp"
    },
    {   "id": 8,
        "name": "Luna",
        "height": "15.1 hands",
        "age": 9,
        "weight": 1280,
        "breed": "Gypsy Vanner",
        "color": "Black and white pibald",
        "gender": "Mare",
        "imageUrl": "../../assets/images/owned/gypsy-mare.webp"
    },
    {   "id": 9,
        "name": "Charlie",
        "height": "12.2 hands",
        "age": 12,
        "weight": 650,
        "breed": "Welsh Pony",
        "color": "Gray",
        "gender": "Gelding",
        "imageUrl": "../../assets/images/owned/welsh-gray.webp"
    },
    {   "id": 10,
        "name": "Rosie",
        "height": "14.3 hands",
        "age": 5,
        "weight": 700,
        "breed": "Pony of the Americas",
        "color": "palamino appaloosa",
        "gender": "Mare",
        "imageUrl": "../../assets/images/owned/poa-mare.webp"
    }
]

